name: Deploy Website

on:
  push:
    branches:
      - main
      - exercicio-web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set Git identity
      run: |
        git config --global user.email "pedro.henrique.gomes@maisunifacisa.com.br"
        git config --global user.name "pedrohsantosg"

    - name: Merge exercicio-vogais branch
      run: |
        git fetch origin
        git checkout exercicio-vogais
        git pull origin exercicio-vogais
        git checkout exercicio-web
        git merge exercicio-vogais

    - name: Merge exercicio-array-person branch
      run: |
        git fetch origin
        git checkout exercicio-array-person
        git pull origin exercicio-array-person
        git checkout exercicio-web
        git merge exercicio-array-person

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: |
        cd exercicioNum03
        npm install

    - name: Build project
      run: |
        cd exercicioNum03
        npm start

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PEDRO_KEY }}
        publish_dir: exercicioNum03

    - name: Finalize build
      run: echo "Build and deployment completed!"
